---
title: "Lizard Lengths"
author: "Jacob Weverka"
date: "12/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)


```

Read in data

```{r}

lizard_data = read_csv(here::here("data/lizards.csv"))

lizards = lizard_data %>%
  select(spp, sex, total_length)


```

Select only females 
```{r}
females = lizards %>%
  filter(spp == "CNUN" | spp == "CNTE",
         sex == "F")
```


```{r include=FALSE}

# Exploratory vizualizations of data looking for normality - don't include in final report!

ggplot(females, aes(x = total_length)) +
  geom_histogram() +
  facet_wrap(. ~ spp)

ggplot(females, aes(sample = total_length)) +
  geom_qq() +
  facet_wrap(. ~ spp)

# Data look fairly normal (mayble slightly deviated from normal)


```

```{r}
length_sum = females %>%
  group_by(spp) %>%
  summarise(mean_length = mean(total_length, na.rm = TRUE), sd_length = sd(total_length, na.rm = TRUE))


length_sum_round = length_sum %>%
  mutate(mean_length = round(mean_length, 2),
         sd_length = round(sd_length, 2))


knitr::kable(length_sum,
             col.names = c("Species", "Mean Length", "SD Length"))
```




```{r}
ggplot() +
  ggbeeswarm::geom_beeswarm(data = females, aes(x = spp, y = total_length),
                            size = 3,
                            alpha = 0.1) +
  geom_point(data = length_sum, aes(x = spp, y = mean_length),
             color = "slateblue4",
             size = 5) +
  geom_errorbar(data = length_sum,
                aes(x = spp,
                    ymin = mean_length - sd_length,
                    ymax = mean_length + sd_length),
                color = "slateblue4",
                width = 0.2) +
  xlab("Species") +
  ylab("Body Length (mm)") +
  scale_x_discrete(name = "Species",
                   labels = c("CNTE" = "Checkered Whiptail", "CNUN" = "Desert Grassland Whiptail")) +
  theme_bw()
```






```{r}
# Now a t-test

cnun = females %>%
  filter(spp == "CNUN") %>%
  pull(total_length)

cnte = females %>%
  filter(spp == "CNTE") %>%
  pull(total_length)

species.t = t.test(cnte, cnun)

species.tidy = broom::tidy(species.t)

```

```{r}
# And a cohen's d effect size

species.d = effsize::cohen.d(cnte, cnun, na.rm = TRUE)


```












